default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nyt_capstone_development
  # template: template0

test:
  <<: *default
  database: nyt_capstone_test
  # template: template0

production:
  <<: *default
  database: nyt_capstone_production
  username: nyt_capstone
  password: <%= ENV['NYT_CAPSTONE_DATABASE_PASSWORD'] %>
